### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by LiuYuHui** [BGI-shenzhen/PopLDdecay#11]
![image](https://user-images.githubusercontent.com/13926137/122680458-dbe67780-d221-11eb-89b1-0bb104c84c42.png)

**Comment by hewm2008** [comment]
This shows that a breakpoint error occurred in the process of reading your VCF file. The reason is most likely caused by **an abnormal format** of a line of your input VCF file. You can check your vcf format first , you can  use  muti  head  -half of the file to check which line is wrong.

**Comment by LiuYuHui** [comment]
Thanks for you suggestions, I will check the format of VCF file.
