### ISSUE TITLE
Error in the plot codes

### ISSUE THREAD

**Issue by jiabowang** [BGI-shenzhen/PopLDdecay#12]
Hi @hewm2008,
Thanks for your useful software. 
I notice that there is a spelling mistake in the plot command.
That should be 
perl  Plot_MultiPop.pl  -inList  Pop.ReslutPath.list  -output Fig 
rather than 
perl  Plot_MutiPop.pl  -inList  Pop.ReslutPath.list  -output Fig

Sincerely,

Jiabo

**Comment by hewm2008** [comment]
thanks 
I just had update the Readme file (ReslutPath--->ResultPath)
