### ISSUE TITLE
Zlib incompatibility

### ISSUE THREAD

**Issue by AldenInversion** [BGI-shenzhen/PopLDdecay#13]
Dear PopLDdecay authors,

Currently I am having issues with installing this software. ./configure is outputting a zlib error, saying the version is not compatible.
My current version of zlib is 1.2.11 on Ubuntu20.04. Screenshot describes the issue.
![20220120_152925](https://user-images.githubusercontent.com/61571258/150295206-6ab8a2b8-fb09-4280-bc87-607ff0354489.jpg)

![20220120_153405](https://user-images.githubusercontent.com/61571258/150295237-f1cd8fc1-3767-452f-85b9-7279a57ad25a.jpg)

**Comment by hewm2008** [comment]
Dear @AldenInversion 
   you can try to check if this file (/usr/lib64/libz.so) exists .    I guess your installation is incomplete 。

   you can **re-try**    [  sudo  yum install -y zlib zlib-devel   ]  or    [   sudo apt-get install  zlib1g-dev  ]   first.

   If it doesn't work, you can send me an email and I will send you a static version
