### ISSUE TITLE
Questions about the "-MAF 0.05" parameter

### ISSUE THREAD

**Issue by scau-drr** [BGI-shenzhen/PopLDdecay#14]
Hi @hewm2008,
Thanks for your useful software.

The script is as follows:
PopLDdecay -InVCF all.final.vcf.gz -SubPop "$pop".list -MaxDist 500 -MAF 0.05 -OutType 1 -OutStat  "$pop".stat.gz

I would like to ask whether this "maf0.05" is for the selected pop population or for all populations ?

Sincerely,

Ding

**Comment by hewm2008** [comment]
dear  Ding
 "maf  0.05" is for the selected sub-pop population.
