### ISSUE TITLE
How to get the distance and r2 value where the LD decay?

### ISSUE THREAD

**Issue by DuttaAnik** [BGI-shenzhen/PopLDdecay#15]
Hi, 
Thank you for developing this wonderful tool. I have plotted genome-wide LD decay for 9 populations as shown in the attached figure. But I was wondering how would I get something like "LD decay dropping to half of its maximum at XX kb" at a specific r2 value.
Can you please tell me a way to get this measurement? Because the figure does not specifically
![all_pop](https://user-images.githubusercontent.com/41111038/160912139-e89cc3ab-a632-4f06-a7d8-752a5a967398.png)
 shows the Kb number on the X-axis where the decay stops.
Thank you.

**Comment by hewm2008** [comment]
Hi：
A    it is best to have the same sample size for comparison of different subgroups (especially when it is in the dozens). 
B    Many paper methods the distance  whe the R^2  is  to take half of the highest point,     or the inflection point when smoothing starts.   or  where the R2==0.2

**Comment by DuttaAnik** [comment]
Thank you very much for the reply. Yes, I used the same number of individuals in each subset.
