### ISSUE TITLE
Process with very long chromosomes

### ISSUE THREAD

**Issue by ChenJuiYANG** [BGI-shenzhen/PopLDdecay#18]
I am working with pine trees with very long chromosomes. 
The largest chromosome has over 2.3G bp long, which cannot be accepted by PLINK and many frequently used programs. 

Can this program work with such long chromosomes? 
Have you ever tested (or in theory) how long of the chromosomes could be accepted?

I tested with my data. It seems worked well, but how do I know all the data has been read and calculated? 
Sorry for asking this. Some programs don't show error message, but over length limit data is not read and processed properly.

**Comment by ChenJuiYANG** [comment]
Ok, I found out the answer now. 
This program cannot process chromosome length longer than 2^31 bp (or 2^31-1 bp). 

I selected the full output and checked the SNP comparison data. As I mentioned in the original question, the longest chromosome is longer than 2.3G bp. The last SNP in chromosome 1 is at position 2364061952, but the last record of sites comparison is 2147467923 vs 2147483647. All SNPs at the position larger than 2^31 are disappeared.  (2^31 = 2147483648) No warning message about this, as many other software. 

Anyway, I can use another file with splitting chromosomes.

**Comment by hewm2008** [comment]
Hi,
your situation is relatively rare. and to apply this situation, the program efficiency will be much slower. 
My suggestion is that you split the Chr1 SNP into chr1A, chr1B, chr1C ... where there is a big gap in the middle of chr1.

best wishes
