### ISSUE TITLE
LD error

### ISSUE THREAD

**Issue by cfz1998** [BGI-shenzhen/PopLDdecay#19]
Hi! @hewm2008 
The sub-population has 51 samples and the LD result seems incorrect.
The reads used for mapping were from the assembled genome(Using `wgsim`).

![image](https://github.com/BGI-shenzhen/PopLDdecay/assets/60096719/aaa4bb37-6aea-4392-9ab4-484a8905e288)

Thank you for your reply!

**Comment by hewm2008** [comment]
Yes, it is recommended not to use simulated data.
