### ISSUE TITLE
Haploview is refered in the manuscript

### ISSUE THREAD

**Issue by nottwy** [BGI-shenzhen/PopLDdecay#2]
I notice that in the github page it said the following analysis was carried out with PopLDdecay.
https://media.nature.com/full/nature-assets/ng/journal/v42/n12/images/ng.715-F1.jpg

But in the manuscript it said the analysis was carried out with Haploview.
It's a little problem and should be clarified, shouldn't it? ;)

**Comment by hewm2008** [comment]
I am the Weiming he (hewm2008),  one of these two paper author. and most of their bioinformatics analysis were carried  by me.
I used the Haploview to carry out the  [50 Rices NBT] and [31 soybeans NG] papers first, but I found it taken too much CPUs and taken up too much hard disk space, so I developed PopLDdecay and compair with Haploview and plink.  I found  PopLDdecay was the best one to plot the LDdecay.  PopLDecay can read the vcf directly， also can  calculate  sub-Popuation  directly, plot the LDdecay 


Use this web site to test follow software ( ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ ) 
only with two based site in chr22  of the 1000 Genomes Project.


| 板本号  |       平均内存              |  核心程序计算时间         | 输入格式转化和结果统计时间        | 输出结果|
| version |    Average memory    |  Core calculation CPUs   | Format conver Statistics Time CPU| result size|

|Plink 1.07             |    1.4G          |      680min                       | 5 min+45min          |         54G
|Plink  2.0              |    18.807G    |      25min                         | 5 min+45min          |         54G
|Haploview  4.2     |   95.760G     |     3904min                      | 5 min+45min          |         54G
|PopLDdcay 3.30   |    2.5G          |     200min                        |  0min                       |         4.1M

**Comment by nottwy** [comment]
PopLDdecay is good indeed and the pictures in the manuscripts were drawn with other tools.
Maybe you drawn them with PopLDdecay but you can't refer it in the manuscript, is it?

**Comment by hewm2008** [comment]
Thanks for your appreciate and suggest.  
To drawn the figure , Providing the perl script of plotting will be more practical and deal more situation, At first of all ,I also want to let the PopLDdecay  give out the fig.svg file directly, however the more other users' plot situations, I gave out and only provided the plotting perl script for all of different Different situations
To refer these two manuscripts just to show the what the result will be. Now with the new Software PopLDdecay was developed, To plot the LDdecay of such figure , PopLDdecay  will be more applicable than Haploview.

**Comment by hewm2008** [comment]
The <i><b>[PopLDDecay article](https://doi.org/10.1093/bioinformatics/bty875)</b></i> has been published in <b> [Bioinformatics](https://doi.org/10.1093/bioinformatics/bty875) magazine</b>, please quote this article if possible
