### ISSUE TITLE
Plot_MultiPop.pl（Error: object 'ECH' not found）

### ISSUE THREAD

**Issue by huang-baisha** [BGI-shenzhen/PopLDdecay#21]
hello,
when I use Plot_MultiPop.pl, I meet the error "Error: object 'ECH' not found".

my command is:
`perl /data/software/PopLDdecay-3.43/bin/Plot_MultiPop.pl -inList SV_pop.list -output SV/SV_pop_Fig`

the content of SV_pop.list is:
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/CH-L_LDdecay.stat.gz CH-L
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/CH-M_LDdecay.stat.gz CH-M
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/IN_LDdecay.stat.gz IN
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/PH_LDdecay.stat.gz PH
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/TW_LDdecay.stat.gz TW

Can you give me some useful suggestions to deal with this problem?
thank you very much!!!

**Comment by hewm2008** [comment]
try to   change  the CH-L  --->  CH_L      CH-M  ---->   CH_M

/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/CH-L_LDdecay.stat.gz CH_L
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/CH-M_LDdecay.stat.gz CH_M
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/IN_LDdecay.stat.gz IN
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/PH_LDdecay.stat.gz PH
/data/hbs/Project/pangenome/Schistosoma_japonicum/LDdecay/SV/TW_LDdecay.stat.gz TW

**Comment by huang-baisha** [comment]
I solved this problem using this method. Thanks!
