### ISSUE TITLE
VCF format issue

### ISSUE THREAD

**Issue by harry-thorpe** [BGI-shenzhen/PopLDdecay#3]
Hi, this tool works great on the example chrom 22 vcf (ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf), but it does not work on mine, which has a slightly different format. When I run it on my vcf, I get a segmentation fault, but no other information. I have uploaded the first few lines of my vcf for you to see (I had to add a .txt extension so that github would accept it).

In my vcf there is no information in the QUAL, FILTER, or INFO columns, could this be the problem? Does PopLDdecay look for some info tag e.g. VT=SNP? Do the variants need IDs? If I know exactly what the tool is looking for then I could modify my vcf to be compatible.

Thanks!
[example.vcf.txt](https://github.com/BGI-shenzhen/PopLDdecay/files/2951895/example.vcf.txt)

**Comment by hewm2008** [comment]
Dear harry-thorpe
I just saw your vcf format, I suggest to make some changes.  haploid  --》  Diploid
you should change the  GT  
  "0"  --->  "0|0"  or  "0/0"
  "1"  --->  "1|1"  or  "1/1"
In theory, the  data of the haploid  --->  diploid  VCF data, which does not affect the change of Decay.


[example.vcf.txt](https://github.com/BGI-shenzhen/PopLDdecay/files/2960759/example.vcf.txt)

such as  : 
`GT	0	0	1	0	...`  
--->
<pre>

##fileformat=VCFv4.1
##contig=<ID=1,length=5398151>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	SPARK_537_C1	SPARK_155_C1	SPARK_1484_C1	SPARK_1516_C1	SPARK_1013_C1	SPARK_1554_C1	SPARK_1330_C1	SPARK_1561_C2	SPARK_8_C1	SPARK_1328_C1	SPARK_1631_C1	SPARK_541_C4	SPARK_1484_C3	SPARK_1539_C2	SPARK_1633_C2	SPARK_1481_C1	SPARK_145_C1	SPARK_1623_C2	SPARK_1623_C1	SPARK_30_C1	SPARK_1494_C2	SPARK_531_C3	SPARK_1482_C1	SPARK_1295_C1	SPARK_1201_C2	SPARK_1460_C2	SPARK_1558_C2	SPARK_251_C2	SPARK_1307_C1	SPARK_1449_C1	SPARK_72_C1	SPARK_1500_C1	SPARK_534_C1	SPARK_536_C1	SPARK_1587_C1	SPARK_534_C2	SPARK_542_C1	SPARK_545_C1	SPARK_811_C2	SPARK_1562_C1	SPARK_726_C1	SPARK_1201_C1	SPARK_155_C2	SPARK_578_C3	SPARK_845_C2	SPARK_555_C1	SPARK_1504_C1	SPARK_1613_C1	SPARK_1447_C1	SPARK_1415_C1	SPARK_162_C1	SPARK_1496_C1	SPARK_1561_C1	SPARK_173_C1	SPARK_1293_C1	SPARK_1345_C1	SPARK_324_C2	SPARK_716_C1	SPARK_1492_C2	SPARK_1494_C3	SPARK_1563_C2	SPARK_44_C1	SPARK_832_C1	SPARK_1630_C1	SPARK_1474_C1	SPARK_1622_C2	SPARK_1498_C1	SPARK_1487_C2	SPARK_597_C2	SPARK_1534_C1	SPARK_1488_C2	SPARK_475_C1	SPARK_878_C2
1	31	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	36	.	G	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	39	.	T	C	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	57	.	A	T	.	.	.	GT	0|0	1|1	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	1|1	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	1|1	1|1	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	0|0	1|1	0|0	1|1	1|1	0|0	1|1	0|0	0|0	0|0	1|1	1|1	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0
1	83	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	90	.	G	A	.	.	.	GT	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
</pre>

**Comment by hewm2008** [comment]
Dear harry-thorpe(@harry-thorpe  )
I just saw your vcf format, I suggest to make some changes.  haploid  --》  Diploid
you should change the  GT  
  "0"  --->  "0|0"  or  "0/0"
  "1"  --->  "1|1"  or  "1/1"
In theory, the  data of the haploid  --->  diploid  VCF data, which does not affect the change of Decay.


[example.vcf.txt](https://github.com/BGI-shenzhen/PopLDdecay/files/2960759/example.vcf.txt)

such as  : 
`GT	0	0	1	0	...`  
--->
<pre>

##fileformat=VCFv4.1
##contig=<ID=1,length=5398151>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	SPARK_537_C1	SPARK_155_C1	SPARK_1484_C1	SPARK_1516_C1	SPARK_1013_C1	SPARK_1554_C1	SPARK_1330_C1	SPARK_1561_C2	SPARK_8_C1	SPARK_1328_C1	SPARK_1631_C1	SPARK_541_C4	SPARK_1484_C3	SPARK_1539_C2	SPARK_1633_C2	SPARK_1481_C1	SPARK_145_C1	SPARK_1623_C2	SPARK_1623_C1	SPARK_30_C1	SPARK_1494_C2	SPARK_531_C3	SPARK_1482_C1	SPARK_1295_C1	SPARK_1201_C2	SPARK_1460_C2	SPARK_1558_C2	SPARK_251_C2	SPARK_1307_C1	SPARK_1449_C1	SPARK_72_C1	SPARK_1500_C1	SPARK_534_C1	SPARK_536_C1	SPARK_1587_C1	SPARK_534_C2	SPARK_542_C1	SPARK_545_C1	SPARK_811_C2	SPARK_1562_C1	SPARK_726_C1	SPARK_1201_C1	SPARK_155_C2	SPARK_578_C3	SPARK_845_C2	SPARK_555_C1	SPARK_1504_C1	SPARK_1613_C1	SPARK_1447_C1	SPARK_1415_C1	SPARK_162_C1	SPARK_1496_C1	SPARK_1561_C1	SPARK_173_C1	SPARK_1293_C1	SPARK_1345_C1	SPARK_324_C2	SPARK_716_C1	SPARK_1492_C2	SPARK_1494_C3	SPARK_1563_C2	SPARK_44_C1	SPARK_832_C1	SPARK_1630_C1	SPARK_1474_C1	SPARK_1622_C2	SPARK_1498_C1	SPARK_1487_C2	SPARK_597_C2	SPARK_1534_C1	SPARK_1488_C2	SPARK_475_C1	SPARK_878_C2
1	31	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	36	.	G	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	39	.	T	C	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	57	.	A	T	.	.	.	GT	0|0	1|1	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	1|1	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	1|1	1|1	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	0|0	1|1	0|0	1|1	1|1	0|0	1|1	0|0	0|0	0|0	1|1	1|1	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0
1	83	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	90	.	G	A	.	.	.	GT	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
</pre>

**Comment by harry-thorpe** [comment]
OK thanks! I also tried converting it to GT format first with plink2genotype.pl, and that worked too.
