### ISSUE TITLE
EHH instructions not clear

### ISSUE THREAD

**Issue by sergiopalmavera** [BGI-shenzhen/PopLDdecay#4]
Hello!

trying to execute the ``EHH`` functionality built in ``PopLDdecay``, I tried the following:

``PopLDdecay -EHH 1:2750001 -InVCF vcf`` 

And got this message:
``lack argument for the must``

But it is not very clear what the message means. 

Also, can a text file be used to provide the sites?

**Comment by hewm2008** [comment]
the  output  para is must . so you can try


PopLDdecay -EHH 1:2750001 -InVCF vcf   -OutStat  OutPrefix



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/28/19,
2:06:42 PM

sergiopalmavera <notifications@github.com> 于2019年5月28日周二 上午10:00写道：

**Comment by hewm2008** [comment]
Hi.
	With VCF files, PopLDdecay can also be used to calculate extended haplotype homozygosity (EHH) (Sabeti, et al., 2002) with the option of   <i>“-EHH”</i>
Output parameters are required，you must set the para [-OutStat],so you can try：  

<pre>
./PopLDdecay -EHH 1:2750001 -InVCF  In.vcf   -OutStat  OutPrefix 
</pre>
