### ISSUE TITLE
Can PopLDdecay use vcf of bacteria as input?

### ISSUE THREAD

**Issue by Xiaojun928** [BGI-shenzhen/PopLDdecay#7]
Hi all,

Thanks for developing such a useful tool.  I am trying to plot the LD along the genome for a bacterial population. So I plan to obtain the vcf using [Snippy](https://github.com/tseemann/snippy) (with snippy-multi, I would get the core SNPs for the population). 
Could you please let me know if PopLDdecay can use this vcf from haploid bacteria?

Thanks and regards,
Xiaojun

**Comment by hewm2008** [comment]
Dear  Xiaojun
if your vcf format is haploid  vcf format, I suggest to make some changes.  haploid  ---》  Diploid
you should change the  GT  
  "0"  --->  "0|0"  or  "0/0"
  "1"  --->  "1|1"  or  "1/1"
In theory, the  data of the haploid  --->  diploid  VCF data, which does not affect the change of Decay.


[example.vcf.txt](https://github.com/BGI-shenzhen/PopLDdecay/files/2960759/example.vcf.txt)

such as  : 
`GT	0	0	1	0	...`  
--->
<pre>

##fileformat=VCFv4.1
##contig=<ID=1,length=5398151>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1	SPARK_537_C1	SPARK_155_C1	SPARK_1484_C1	SPARK_1516_C1	SPARK_1013_C1	SPARK_1554_C1	SPARK_1330_C1	SPARK_1561_C2	SPARK_8_C1	SPARK_1328_C1	SPARK_1631_C1	SPARK_541_C4	SPARK_1484_C3	SPARK_1539_C2	SPARK_1633_C2	SPARK_1481_C1	SPARK_145_C1	SPARK_1623_C2	SPARK_1623_C1	SPARK_30_C1	SPARK_1494_C2	SPARK_531_C3	SPARK_1482_C1	SPARK_1295_C1	SPARK_1201_C2	SPARK_1460_C2	SPARK_1558_C2	SPARK_251_C2	SPARK_1307_C1	SPARK_1449_C1	SPARK_72_C1	SPARK_1500_C1	SPARK_534_C1	SPARK_536_C1	SPARK_1587_C1	SPARK_534_C2	SPARK_542_C1	SPARK_545_C1	SPARK_811_C2	SPARK_1562_C1	SPARK_726_C1	SPARK_1201_C1	SPARK_155_C2	SPARK_578_C3	SPARK_845_C2	SPARK_555_C1	SPARK_1504_C1	SPARK_1613_C1	SPARK_1447_C1	SPARK_1415_C1	SPARK_162_C1	SPARK_1496_C1	SPARK_1561_C1	SPARK_173_C1	SPARK_1293_C1	SPARK_1345_C1	SPARK_324_C2	SPARK_716_C1	SPARK_1492_C2	SPARK_1494_C3	SPARK_1563_C2	SPARK_44_C1	SPARK_832_C1	SPARK_1630_C1	SPARK_1474_C1	SPARK_1622_C2	SPARK_1498_C1	SPARK_1487_C2	SPARK_597_C2	SPARK_1534_C1	SPARK_1488_C2	SPARK_475_C1	SPARK_878_C2
1	31	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	36	.	G	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	39	.	T	C	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	57	.	A	T	.	.	.	GT	0|0	1|1	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	1|1	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	1|1	1|1	1|1	0|0	0|0	0|0	1|1	0|0	1|1	0|0	0|0	1|1	0|0	1|1	1|1	0|0	1|1	0|0	0|0	0|0	1|1	1|1	0|0	0|0	1|1	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0
1	83	.	C	T	.	.	.	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
1	90	.	G	A	.	.	.	GT	0|0	0|0	1|1	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0
</pre>

**Comment by Xiaojun928** [comment]
Thanks very much for your suggestions! I can try it now.

Best regards,
Xiaojun

**Comment by hewm2008** [comment]
Here  is the perl script ： perl    xxx.pl    InPut.vcf     OutPut.vcf
<pre>
#!/usr/bin/perl -w
use strict;
#Version 1.0    hewm2008@qq.com
die  "Version 1.0\t2021-04-23;\nUsage: $0  InPut.vcf   OutPut.vcf   \n" unless (@ARGV ==2);

#############Befor  Start  , open the files ####################

my $InPutFile=$ARGV[0];
if ($InPutFile=~s/.gz$/.gz/g)
{
        open (IA,"gzip -cd $InPutFile | ") || die "input file can't open $!";
}
else
{
        open (IA,"$InPutFile") || die "input file can't open $!";
}

open (OA,">$ARGV[1]") || die "output file can't open $!" ;

################ Do what you want to do #######################

while(<IA>)
{
        chomp ;
        if ($_=~s/#/#/)
        {
                print OA  $_,"\n";
                next;
        }
        else
        {
                my @inf=split ;
                # next if ($inf[3]=~/,/  ||  $inf[4]=~/,/ )  ; # muti base
                next if (length($inf[3])>1); #  InDel
                next if (length($inf[4])>1); #  InDel  or muti base
                $inf[8]="GT";
                foreach my $k (9..$#inf)
                {
                        my $base=substr($inf[$k],0,1);
                        $inf[$k]="$base|$base";
                }
                $_=join("\t",@inf);
                print OA "$_\n";
        }
}
close IA;
close OA ;
######################swimming in the sky and flying in the sea ###########################

</pre>
