### ISSUE TITLE
VCF file example 

### ISSUE THREAD

**Issue by NurislamSheih** [BGI-shenzhen/PopLDdecay#9]
Dear @hewm2008,

Could you please share vcf file that you used to test program? I'm trying to use PopLDdecay on my gatk processed vcf file, but it gives empty file. Maybe my vcf files are not in the correct format.

**Comment by hewm2008** [comment]
A.   The samples number in the VCF format file must be more than 5, and the samples can only be **diploid** samples, if it is a **haploid/haplotype**, you can **[ see here  ](https://github.com/BGI-shenzhen/PopLDdecay/issues/7)** how to pre-deal 2 diploid ;

B . The VCF file  format you can see at this [web site ](https://www.internationalgenome.org/wiki/Analysis/vcf4.0/);   VCF [4.0](https://www.internationalgenome.org/wiki/Analysis/vcf4.0/)  [4.2 ](https://samtools.github.io/hts-specs/VCFv4.2.pdf) [4.3 ](https://en.wikipedia.org/wiki/Variant_Call_Format)is ok.

C. The  test VCF  is the  chr22.vcf   at this[ website](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/) .   To test the accuracy and the efficiency of PopLDdecay, we used data of this web site(ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502) to test follow software, only with two based site in chr22 (minimal chromosome SNP database)  (2504 sample with 1,055,401 SNP numbers)to test these software.

**Comment by NurislamSheih** [comment]
@hewm2008 Thank you for answer!

My vcf file contain only one sample, that why PopLDdecay doesn't work, how I understand.
